GET http://localhost:3000/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiVmljdG9yIiwiY3JlYXRlZEF0IjoxNjAxNTU4NDUwLCJleHBpcmVkQXQiOjE2MDE1NTg3NTB9.3kg1diZxU-yGGG8UuW5MtZ0fTLwsMrLwLbKBomdL7Ls

###

POST http://localhost:3000/api/proyectos
Content-Type: application/json

{
    "titulo": "Proyecto de json",
    "descripcion": "Esta es la descripcion",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.es/quien-somos"
}

###

PUT http://localhost:3000/api/proyectos/5f75c07c338b172ce43e60ad
Content-Type: application/json

{
    "titulo": "Proyecto editado 7",
    "descripcion": "Esta es la descripcion editada",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.es/quien-somos"
}

###

DELETE http://localhost:3000/api/proyectos/5f75d1d038de973280125808

###

GET http://localhost:3000/api/token