### Obtener todas las inversiones
GET http://localhost:3000/api/inversiones

### Crear nueva inversión
POST http://localhost:3000/api/inversiones
Content-Type: application/json

{
    "anoCompra": 2020,
    "mesCompra": "septiembre",
    "accion": "ACS",
    "precioAccionCompra": 15,
    "totalCompra": 2015,
    "comisionCompra": 15,
    "anoVenta": 2020,
    "mesVenta": "mayo",
    "precioAccionVenta": 20,
    "totalVenta": 2000,
    "comisionVenta": 10,
    "dividendoBruto": 20
}

### Modificar una inversión
PUT http://localhost:3000/api/inversiones

### Eliminar una inversión
DELETE http://localhost:3000/api/inversiones
